import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=process.env.QA_NODE_MODULES?require(path.join(process.env.QA_NODE_MODULES,'playwright')):require('playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const output=path.join(root,'tests/screenshots');const evidence=process.env.QA_REMAINING?JSON.parse(fs.readFileSync(path.join(root,'tests/audio-evidence.json'))):{};let broken=null;const requests=[];
const server=http.createServer((req,res)=>{const url=req.url.split('?')[0];requests.push(url);const prefix=url.startsWith('/baseline/')?'baseline':url.startsWith('/qa/')?'qa':'hide-and-seek';let file=prefix==='baseline'?path.join(root,'tests/fixtures/phase35-sound.js'):path.join(root,decodeURIComponent(url).replace(/^\/(qa|baseline|hide-and-seek)/,''));if(file.endsWith('/'))file+='index.html';if(broken&&url.endsWith('/audio/'+broken+'.mp3')){res.writeHead(404,{'Cache-Control':'no-store'});res.end('fault injection');return;}try{let bytes=fs.readFileSync(file);if(prefix==='qa'&&file.endsWith('app.js'))bytes=Buffer.from(bytes.toString().replace('const camera=new Camera();','const camera=new Camera();globalThis.__testCamera=camera;globalThis.__testSound=sound;globalThis.__testMini=mini;'));if(prefix==='qa'&&file.endsWith('engine.js'))bytes=Buffer.from(bytes.toString().replace('this.random=random;','globalThis.__testGame=this;this.random=random;'));res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.mp3':'audio/mpeg','.png':'image/png','.webmanifest':'application/manifest+json'})[path.extname(file)]||'text/plain','Content-Length':bytes.length});res.end(bytes);}catch{res.writeHead(404);res.end('not found');}});
await new Promise(resolve=>server.listen(8767,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--autoplay-policy=document-user-activation-required'],env:process.env});
const errors=[];let debugPage;
// Test-only meters measure decoded output, not just calls to play(). Nodes also connect to audio destination.
async function meters(context){await context.addInitScript(()=>{window.__meters=[];const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){const promise=play.call(this);Promise.resolve(promise).then(()=>{const ctx=window.__testSound?.ctx;if(!ctx||this.__meter)return;try{const source=ctx.createMediaElementSource(this),meter=ctx.createAnalyser();meter.fftSize=1024;source.connect(meter);meter.connect(ctx.destination);this.__meter=meter;window.__meters.push({element:this,meter});}catch(e){window.__meterError=String(e);}}).catch(()=>{});return promise;};});}
async function signal(page,filename){return page.evaluate(filename=>{const items=window.__meters.filter(v=>v.element.src.endsWith('/'+filename+'.mp3'));let peak=0,rms=0,count=0;for(const {element,meter} of items){const data=new Float32Array(meter.fftSize);meter.getFloatTimeDomainData(data);for(const v of data){peak=Math.max(peak,Math.abs(v));rms+=v*v;count++;}}return {peak,rms:Math.sqrt(rms/Math.max(1,count)),nodes:items.length,playing:items.filter(v=>!v.element.paused).length};},filename);}
async function nonzero(page,name){await page.waitForFunction(name=>window.__meters.some(({element,meter})=>{if(!element.src.endsWith('/'+name+'.mp3')||element.paused)return false;const d=new Float32Array(meter.fftSize);meter.getFloatTimeDomainData(d);return d.some(v=>Math.abs(v)>.0001);}),name,{timeout:12000});return signal(page,name);}
async function freeze(page){await page.evaluate(()=>{const g=window.__testGame;g.onis.forEach(o=>Object.assign(o,{x:60,y:570,wait:999,route:[],target:null,inspect:null}));g.characters.forEach(c=>{c.decision=999;c.grace=999;});});}
try{
 let context,page;
 if(!process.env.QA_REMAINING){
 // Reproduce the old all-or-nothing loader and useless retry without inventing a device-specific cause.
 const oldContext=await browser.newContext({serviceWorkers:'block'}),old=await oldContext.newPage();broken='spotted';await old.goto('http://127.0.0.1:8767/qa/');await old.evaluate(async()=>{const {Sound}=await import('/baseline/sound.js');window.__old=new Sound();document.querySelector('#start').onclick=()=>window.__old.start();});await old.locator('#start').click();await old.waitForFunction(()=>window.__old.failed&&window.__old.buffers.park);evidence.oldFailure=await old.evaluate(()=>({failed:window.__old.failed,parkDecoded:!!window.__old.buffers.park,loops:Object.keys(window.__old.loops).length}));await old.evaluate(()=>{window.__old.setEnabled(false);window.__old.setEnabled(true);});assert.equal(await old.evaluate(()=>Object.keys(window.__old.loops).length),0);await oldContext.close();broken=null;console.log('OLD FAILURE REPRODUCED',evidence.oldFailure);
 context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await meters(context);page=await context.newPage();debugPage=page;page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:8767/qa/');assert.equal(await page.evaluate(()=>Object.keys(window.__testSound.players).length),0);await page.getByRole('button',{name:'かくれんぼ スタート'}).tap();await freeze(page);evidence.park=await nonzero(page,'park');await page.waitForFunction(()=>window.__testSound.players.park.volume>.35);evidence.start=await page.evaluate(()=>({ctx:window.__testSound.ctx.state,status:window.__testSound.status,mode:window.__testSound.mode,currentTime:window.__testSound.players.park.currentTime}));assert.equal(evidence.start.ctx,'running');assert.equal(evidence.start.status.park.play,'playing');assert(!await page.locator('#audioRetry').isVisible());
 await page.evaluate(()=>{const g=window.__testGame;Object.assign(g.onis[1],{x:210,y:310,angle:0});Object.assign(g.controlled,{x:265,y:310,point:9,route:[],state:'hidden',grace:0});});await page.waitForFunction(()=>window.__testSound.mode==='danger');evidence.danger=await nonzero(page,'danger');await page.screenshot({path:path.join(output,'two-oni-danger.png')});evidence.spotted=await nonzero(page,'spotted');evidence.captured=await nonzero(page,'captured');assert.equal(await page.evaluate(()=>window.__testSound.metrics.spotted),1);assert.equal(await page.evaluate(()=>window.__testSound.metrics.captured),1);assert.equal(await page.evaluate(()=>window.__testGame.controlledId),1);await freeze(page);await page.waitForFunction(()=>window.__testSound.mode==='park'&&window.__testSound.players.park.volume>.35);evidence.return=await nonzero(page,'park');
 await page.getByRole('button',{name:'音を切る'}).tap();assert.equal(await page.evaluate(()=>Object.keys(window.__testSound.loops).length),0);await page.waitForFunction(()=>window.__testSound.ctx.state==='suspended');assert.equal((await signal(page,'park')).playing,0);await page.getByRole('button',{name:'音を出す'}).tap();evidence.onAgain=await nonzero(page,'park');console.log('START/CROSSFADE/SPOTTED/CAPTURED/OFF/ON OUTPUT PASS',JSON.stringify(evidence));await page.getByRole('button',{name:'一時停止',exact:true}).tap();assert.equal((await signal(page,'park')).playing,0);await page.getByRole('button',{name:'再開 ▶',exact:true}).tap();await nonzero(page,'park');
 // Preserve the previous touch UX checks; also capture the notice during its pause.
 await page.evaluate(()=>{const g=window.__testGame;Object.assign(g.controlled,{x:53,y:303,point:9,origin:9,destination:9,state:'hidden',route:[],grace:999});Object.assign(g.characters[2],{x:53,y:275,point:3,state:'hidden',route:[],grace:999});window.__testCamera.center(53,303);});const r=await page.locator('canvas').boundingBox(),cam=await page.evaluate(()=>({x:window.__testCamera.x,y:window.__testCamera.y}));await page.touchscreen.tap(r.x+r.width*(53-cam.x)/420,r.y+r.height*(275-cam.y)/600);await page.waitForFunction(()=>window.__testGame.controlled.noticeUntil>window.__testGame.elapsed);const pause=await page.evaluate(()=>({x:window.__testGame.controlled.x,y:window.__testGame.controlled.y}));await page.waitForTimeout(150);assert.deepEqual(await page.evaluate(()=>({x:window.__testGame.controlled.x,y:window.__testGame.controlled.y})),pause);await page.evaluate(()=>{window.__realUpdate=window.__testGame.update;window.__testGame.update=()=>{};});await page.screenshot({path:path.join(output,'occupied-notice.png')});await page.evaluate(()=>{window.__testGame.update=window.__realUpdate;});await page.waitForFunction(()=>window.__testGame.controlled.noticeUntil<=window.__testGame.elapsed);await page.waitForTimeout(100);assert.notDeepEqual(await page.evaluate(()=>({x:window.__testGame.controlled.x,y:window.__testGame.controlled.y})),pause);
 await page.evaluate(()=>{const g=window.__testGame;Object.assign(g.controlled,{x:515,y:85,point:11,state:'hidden',route:[]});window.__testCamera.center(515,85);window.__testMini.x=324;window.__testMini.holdUntil=0;});await page.waitForFunction(()=>window.__testMini.x===12);await page.screenshot({path:path.join(output,'minimap-retreat.png')});await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>window.__testMini.x),12);
 await page.evaluate(()=>window.__testGame.characters.forEach(c=>window.__testGame.capture(c)));await page.locator('#resultPanel').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>Object.keys(window.__testSound.loops).length),0);assert(await page.evaluate(()=>window.__testSound.effects.size>0));await page.getByRole('button',{name:'もういちど あそぶ'}).tap();await freeze(page);evidence.restart=await nonzero(page,'park');
 }else{context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await meters(context);page=await context.newPage();debugPage=page;page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>console.log('PAGE',m.type(),m.text()));await page.goto('http://127.0.0.1:8767/qa/');await page.locator('#start').tap();await freeze(page);await nonzero(page,'park');console.log('CONTINUING REMAINING PWA/FAULT TESTS');}
 console.log('SW',await page.evaluate(async()=>({registration:!!await navigator.serviceWorker.getRegistration(),cache:await caches.keys()})));await page.evaluate(async()=>Promise.race([navigator.serviceWorker.ready,new Promise((_r,reject)=>setTimeout(()=>reject(Error('SW ready timeout')),15000))]));await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);await page.close();page=await context.newPage();debugPage=page;page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:8767/qa/');await page.getByRole('button',{name:'かくれんぼ スタート'}).tap();await freeze(page);evidence.offline=await nonzero(page,'park');await page.evaluate(()=>{window.__testSound.setMode('danger');window.__testGame.focus.remaining=3;});evidence.offlineDanger=await nonzero(page,'danger');await context.close();console.log('OUTPUT SIGNALS',evidence);
 // For each individual failed file, healthy tracks keep playing. Retry must fetch and really recover.
 for(const failed of ['park','danger','spotted','captured']){
  const faultContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block'});await meters(faultContext);const p=await faultContext.newPage();broken=failed;await p.goto('http://127.0.0.1:8767/qa/');await p.getByRole('button',{name:'かくれんぼ スタート'}).tap();await freeze(p);await p.locator('#audioRetry').waitFor({state:'visible'});await nonzero(p,failed==='park'?'danger':'park');
  const healthySE=failed==='spotted'?'captured':'spotted';await p.evaluate(key=>window.__testSound.effect(key,800),healthySE);await nonzero(p,healthySE);
  if(failed==='danger'){await p.evaluate(()=>{window.__testGame.focus.remaining=5;window.__testSound.setMode('danger');});await p.waitForFunction(()=>window.__testSound.audibleMode==='park');await nonzero(p,'park');}
  const before=requests.filter(url=>url.endsWith('/audio/'+failed+'.mp3')).length;broken=null;await p.locator('#audioRetry').tap();await p.locator('#audioRetry').waitFor({state:'hidden'});await p.waitForFunction(key=>window.__testSound.status[key].load==='ready',failed);assert(requests.filter(url=>url.endsWith('/audio/'+failed+'.mp3')).length>before);
  if(['park','danger'].includes(failed)){await p.evaluate(key=>{window.__testSound.setMode(key);window.__testGame.focus.remaining=key==='danger'?5:0;},failed);await nonzero(p,failed);}else{await p.evaluate(key=>window.__testSound.effect(key,900),failed);await nonzero(p,failed);}
  evidence['retry-'+failed]={freshRequest:true,restoredOutput:true};await faultContext.close();console.log('ISOLATED FAILURE + RETRY PASS',failed);
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(root,'tests/audio-evidence.json'),JSON.stringify(evidence,null,2));console.log('PASS: native play success + nonzero PCM output, all transitions, mute/ON, restart, offline, all four isolated failures and real retries, minimap and notice UX');
}catch(e){console.log('DEBUG',errors,await debugPage?.evaluate(()=>({startHidden:document.querySelector('#startPanel')?.hidden,state:window.__testGame?.state,clock:document.querySelector('#clock')?.textContent,audio:window.__testSound?.status,sw:navigator.serviceWorker.controller?.scriptURL})).catch(()=>null));throw e;}finally{fs.writeFileSync(path.join(root,'tests/audio-evidence.json'),JSON.stringify(evidence,null,2));broken=null;await browser.close();server.close();}
