import assert from 'node:assert/strict';
import {Game,points,pathfind,lineClear,VISION,sightPolygon,rescueRules,RESCUE_POINT} from '../engine.js';
import {DangerMusic,Sound,TRACKS} from '../sound.js';
const rng=seed=>()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
const run=(g,t)=>{for(let i=0;i<Math.ceil(t*60)&&g.state==='playing';i++)g.update(1/60);};
function freeze(g){g.characters.forEach(c=>{c.decision=999;c.grace=999;});g.onis.forEach(o=>Object.assign(o,{route:[],wait:999,inspect:null,target:null}));}
// Each enemy independently detects front, moving, side/back, occlusion, with notice grace.
for(const id of [0,1]){const g=new Game(60,rng(2));freeze(g);const o=g.onis[id];Object.assign(o,{x:210,y:310,angle:0});Object.assign(g.controlled,{x:265,y:310,point:9,grace:0});assert(g.visible(g.controlled,VISION.range,VISION.halfAngle,o));g.update(.05);assert.notEqual(g.controlled.state,'spotted');run(g,3);assert(g.events.some(e=>e.type==='spotted'&&e.oni===id));assert.equal(g.characters[0].state,'captured');assert.equal(g.stats.discoveries,1);assert.equal(g.stats.captures,1);}
const geometry=new Game();freeze(geometry);Object.assign(geometry.oni,{x:210,y:310,angle:0});const c=geometry.controlled;Object.assign(c,{x:210,y:380,grace:0});assert(!geometry.visible(c));Object.assign(c,{x:145,y:310});assert(!geometry.visible(c));Object.assign(geometry.oni,{x:40,y:500,angle:0});Object.assign(c,{x:134,y:500,point:2});assert(!geometry.visible(c));run(geometry,3);assert.equal(geometry.stats.discoveries,0);assert(sightPolygon(geometry.oni).every(p=>p.x<=117.001));
const walking=new Game();freeze(walking);Object.assign(walking.oni,{x:210,y:310,angle:0});Object.assign(walking.controlled,{x:265,y:310,point:null,destination:12,grace:0,state:'moving',route:pathfind({x:265,y:310},points[12])});run(walking,1.5);assert(walking.stats.discoveries>0);
const bush=new Game();freeze(bush);Object.assign(bush.oni,{x:90,y:275,angle:Math.PI});Object.assign(bush.controlled,{...points[3],point:3,grace:0});run(bush,4);assert(bush.stats.discoveries>0); // Concealment buys seconds, never invisible indefinitely.
const simultaneous=new Game();freeze(simultaneous);simultaneous.onis.forEach(o=>Object.assign(o,{x:210,y:310,angle:0}));Object.assign(simultaneous.controlled,{x:265,y:310,point:9,grace:0});run(simultaneous,3);assert.equal(simultaneous.events.filter(e=>e.type==='spotted'&&e.id===0).length,1);assert.equal(simultaneous.events.filter(e=>e.type==='capture'&&e.id===0).length,1);assert(simultaneous.onis.every(o=>o.target!==0));
// Occupancy discovered near the destination, with continuous movement and another shelter.
const capacity=new Game();freeze(capacity);Object.assign(capacity.characters[1],{...points[3],point:3});assert(capacity.move(0,3));assert.equal(capacity.controlled.destination,3);let previous={x:capacity.controlled.x,y:capacity.controlled.y},denied=false;
for(let i=0;i<1800;i++){capacity.update(1/60);const now=capacity.characters[0];assert(Math.hypot(now.x-previous.x,now.y-previous.y)<=61/60+.001);previous={x:now.x,y:now.y};if(capacity.stats.occupied){denied=true;assert(capacity.events.some(e=>e.type==='occupied'&&e.point===3));}const used=new Set();for(const actor of capacity.characters){if(actor.point!==null&&points[actor.point].capacity===1&&actor.state!=='captured'){assert(!used.has(actor.point));used.add(actor.point);}}if(denied&&now.state==='hidden')break;}
assert(denied);assert.notEqual(capacity.controlled.point,3);assert.equal(capacity.characters[1].point,3);
// Concurrent COM arrivals; one enters, the second notices the occupant without a reservation.
const com=new Game();freeze(com);for(const id of [1,2])Object.assign(com.characters[id],{x:65,y:287,point:9,origin:9,state:'hidden'});assert(com.move(1,3));assert(com.move(2,3));run(com,3);assert.equal(com.characters.filter(c=>c.point===3).length,1);assert(com.stats.occupied>0);
const fallback=new Game();freeze(fallback);Object.assign(fallback.controlled,{x:53,y:294,point:null,origin:9,state:'moving',destination:3,route:[{x:53,y:275}]});Object.assign(fallback.characters[1],{...points[3],point:3});fallback.available=(p,id)=>p===9;fallback.update(.01);assert.equal(fallback.controlled.destination,9);assert(fallback.controlled.route.length);assert(Math.hypot(fallback.controlled.x-53,fallback.controlled.y-294)<=.611);
const rescue=new Game();freeze(rescue);rescue.capture(rescue.characters[0]);rescue.capture(rescue.characters[2]);assert.equal(rescue.controlledId,1);Object.assign(rescue.controlled,{...points[RESCUE_POINT],point:RESCUE_POINT,state:'hidden'});assert(rescue.rescue(rescue.controlled));assert.equal(rescue.stats.released,2);assert.equal(rescue.controlledId,1);assert(rescue.characters[0].route.length);run(rescue,8);const shelters=rescue.characters.filter(c=>c.point!==null&&points[c.point].capacity===1).map(c=>c.point);assert.equal(new Set(shelters).size,shelters.length);
// Max risk, focus cooldown, real clock unaffected by slow, independent patrol tracks.
const max=new Game();freeze(max);Object.assign(max.onis[1],{x:210,y:310,angle:0});Object.assign(max.controlled,{x:265,y:310,point:9,grace:0});assert(max.risk(max.controlled)>.59);assert.equal(max.dangerousOni.id,1);max.update(.02);assert.equal(max.stats.focuses,1);assert.equal(max.remaining,59.98);assert(max.focus.scale<1);max.controlled.grace=999;run(max,7);assert.equal(max.stats.focuses,1);
const rounds=[];for(let seed=1;seed<=30;seed++){const g=new Game(60,rng(seed));const locations=g.onis.map(o=>({x:o.x,y:o.y}));assert.notDeepEqual(locations[0],locations[1]);run(g,61);assert.equal(g.state,'ended');assert(g.stats.comMoves>0);assert(g.stats.patrols>0);rounds.push({seed,reason:g.result.reason,survivors:g.result.survivors,...g.stats});}assert(rounds.some(g=>g.rescues));
const late=new Game(60,rng(1),{...rescueRules,lateOniAt:.27});freeze(late);late.remaining=15;late.update(.01);late.update(.01);assert.equal(late.onis.length,3);assert.equal(late.events.filter(e=>e.type==='oni-added').length,1);
// Sound state hysteresis and mute/restart/transition idempotence with a deterministic audio adapter.
const music=new DangerMusic();assert.equal(music.update(.58,false,.01),'danger');for(let i=0;i<40;i++)assert.equal(music.update(i%2?.56:.35,false,.1),'danger');assert.equal(music.update(.2,false,1.7),'danger');assert.equal(music.update(.2,false,.11),'park');assert.equal(music.update(0,true,.01),'danger');
const sources=[];class FakeSource{connect(){}start(){this.started=true;}stop(){this.stopped=true;}}
class FakeGain{constructor(){this.gain={value:0,cancelAndHoldAtTime(){},linearRampToValueAtTime(v,t){this.value=v;this.time=t;}};}connect(){}}
const sound=new Sound();sound.ctx={currentTime:0,state:'running',createBufferSource(){const s=new FakeSource();sources.push(s);return s;},createGain(){return new FakeGain();},resume(){return Promise.resolve();}};sound.buffers=Object.fromEntries(Object.keys(TRACKS).map(k=>[k,{}]));sound.loadPromise=Promise.resolve();sound.start();await Promise.resolve();assert.equal(Object.keys(sound.loops).length,2);assert(Object.values(sound.loops).every(t=>t.source.loop));sound.setMode('danger');assert.equal(sound.loops.danger.gain.gain.value,TRACKS.danger.volume);assert.equal(sound.loops.park.gain.gain.value,0);assert.equal(sound.loops.danger.gain.gain.time,.65);
sound.effect('spotted',1);sound.effect('spotted',1);sound.effect('captured',2);sound.effect('captured',2);assert.equal(sound.metrics.spotted,1);assert.equal(sound.metrics.captured,1);assert.equal(sound.effects.size,2);sound.setEnabled(false);assert.equal(sound.effects.size,0);assert.equal(Object.keys(sound.loops).length,0);assert(sources.every(s=>s.stopped));sound.setEnabled(true);await Promise.resolve();assert.equal(sound.mode,'danger');assert.equal(sound.loops.danger.gain.gain.value,TRACKS.danger.volume);sound.pause();assert.equal(Object.keys(sound.loops).length,0);sound.resume();await Promise.resolve();assert.equal(Object.keys(sound.loops).length,2);sound.start();await Promise.resolve();assert.equal(sound.mode,'park');sound.stop();
console.log('PASS: independent enemies / sight grace and blockers / moving detection / simultaneous transitions / capacity continuous reroute and fallback / COM and rescue / max risk / focus / 30 full rounds / optional late oni / crossfade hysteresis SE mute resume restart');
console.log(JSON.stringify(rounds));
